In [2]:
import numpy as np

In [12]:
l2 = [1,2,'a']
print(type(l2))
array2 = np.array(l2)
print(type(array2))

<class 'list'>
<class 'numpy.ndarray'>


In [25]:
# dtype 을 변경해보기
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') # float64 bit 를 많이 활용한다
print(array_float, array_float.dtype)

# array float -> array int
array_float1 = np.array([1.1,1.2,3.3])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 1 3] int32


### arange,zeros,ones 살펴보기

In [31]:
for i in range(3):
    print(i, end=' ')

0 1 2 

In [29]:
# 기준셀 위에 추가:: a(above)
# 기준셀 아래 추가:: b(below)
# 선택된 셀을 지우고 싶다면:: x
# 실수로 선택된 셀을 지웠다면:: z

In [34]:
# np.arange를 살펴보기
sq_array = np.arange(10)
print(sq_array)
print(sq_array.dtype, sq_array.shape)

## 위의 자료를 2차원으로 표현하고 싶다면?
# np.array([[0,1,2,3,4,5,6,7,8,9]]).shape

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [36]:
# zeros 함수
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array.dtype, zero_array.shape)

int32 (3, 2)


In [45]:
# reshape 함수 실습
array2 = sq_array.reshape(2,5) # 고정된 상수 2와 5로 변환
array3 = array2.reshape(-1,1) # 하나의 컬럼에 데이터가 달린 형태
array3.reshape(-1,2)

# 의도적 오류
array3.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [58]:
# 3차원 ndarray 를 생성
array1 = np.arange(8)
array3d = array1.reshape((2,2,2)) # 3차원의 데이터
print('array3d\n', array3d.tolist()) # array -> list 
print('\n', array3d)

## 3차원 ndarray 를 2차원 ndarray 로 변환
array3d.reshape(-1,4).tolist()

array3d
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[[0, 1, 2, 3], [4, 5, 6, 7]]

### ndarray 데이터 셋 인덱싱

* numpy 에서의 ndarray 내에서 특정 데이터 혹은 일부를 선택

#### 1. 특정 데이터 추출
#### 2. 슬라이싱(slicing)
#### 3. fancy indexing
#### 4. boolean indexing

In [64]:
# 1~9 까지의 데이터 생성
array1 = np.arange(start=1, stop=10)

# index [0]부터 시작
array1
value = array1[2]
print('value:', value)
print(type(value))

value: 3
<class 'numpy.int32'>


In [68]:
print('맨 뒤의 값:', array1[-1],'맨 뒤의 두번째 값:', array1[-2])
array1[0]=9
array1[8]=0
array1

맨 뒤의 값: 9 맨 뒤의 두번째 값: 8


array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [77]:
# 2차원에 해당하는 인덱싱 :: 특정값 출력
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


### 1. 특정 데이터 추출

In [93]:
# 1차원에 해당하는 인덱싱 :: 슬라이싱 추출
array1d
array1d_1 = array1d[:3]
print(array1d_1)
print(array1d[3:])
print(array1d[:])

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


### 2. 슬라이싱 인덱싱

In [106]:
# 2차원에 해당하는 인덱싱 :: 슬라이싱 추출
array2d = array1d.reshape(3,3)
print(array2d)

# print('array2d:\n', array2d[0:2,0:2])
# print('array2d:\n', array2d[1:,])
print('array2d:\n', array2d[0:2,0])  # 1차원
print('array2d:\n', array2d[0:2,:1]) # 2차원

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d:
 [[1 2]
 [4 5]]
array2d:
 [1 4]
array2d:
 [[1]
 [4]]


### 3. 팬시 인덱싱(Fancy indexing)

In [96]:
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [105]:
answer1 = array2d[0:2,0] # 슬라이싱을 활용한 인덱싱
print('array2d[0:2,0]->', answer1.tolist())

answer2 = array2d[[0,1],0] # 특정값 추출을 활용한 인덱싱
print('array2d[[0,1],0]->', answer2.tolist())

## 2차원 형태로 인덱싱
answer3 = array2d[[0,1],0:1] # 특정값 추출을 활용한 인덱싱
print('array2d[[0,1],0:1]->', answer3.tolist())

# 핵심
array2d[[0,1]]

array2d[0:2,0]-> [1, 4]
array2d[[0,1],0]-> [1, 4]
array2d[[0,1],0:1]-> [[1], [4]]


array([[1, 2, 3],
       [4, 5, 6]])

### 4. 불리언 인덱싱(Boolean Indexing)

In [115]:
# 원본 데이터
print(array1d)
print(array1d[array1d>5])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [119]:
for i in array1d:
    if i>5:
        print(i)
    else:
        pass

6
7
8
9


In [123]:
# array1d[array1d>5]와의 비교
boolean_index = np.array([False, False, False, False, False,  True,  True,  True,  True])
array1d[boolean_index]

array([6, 7, 8, 9])

### sort()와 argsort()함수 실습

### summary :: 원본을 변환시키는 함수는 return 값이 없으므로 출력값이 없는 겁니다
* 만약 원본을 유지시키는 함수라면 return 값을 받을 것이므로 출력값이 있게 됩니다

In [129]:
# list에 해당하는 sort()
a = [1,4,2,3]
a.sort()
print(a)
a # 원본이 변환되어 있음..

[1, 2, 3, 4]


In [130]:
## 출력값이 없는 함수의 사례
def add(x,y):
#     print("%d, %d의 합은 %d입니다" % (x,y, x+y))
    return x+y
result = add(x=3,y=5)
print(result)

8


In [138]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()를 통해 정렬
sorted_array1 = np.sort(org_array) # numpy 패키지의 sort 적용
print('np.sort() 적용 후 원본 행렬:', org_array)
print('np.sort() 적용 후 정렬 행렬:', sorted_array1)

# ndarray.sort()를 통해 정렬
sorted_array2 = org_array.sort() # 기본함수 sort 적용
print('ndarray.sort() 적용 후 원본 행렬:', org_array)
print('ndarray.sort() 적용 후 정렬 행렬:', sorted_array2)

# summary :: 원본을 변환시키는 함수는 return 값이 없으므로 출력값이 없는 겁니다
# 만약 원본을 유지시키는 함수라면 return 값을 받을 것이므로 출력값이 있게 됩니다

원본 행렬: [3 1 9 5]
np.sort() 적용 후 원본 행렬: [3 1 9 5]
np.sort() 적용 후 정렬 행렬: [1 3 5 9]
ndarray.sort() 적용 후 원본 행렬: [1 3 5 9]
ndarray.sort() 적용 후 정렬 행렬: None
