## 01 사이킷런 소개와 특징

사이킷런(scikit-learn)은 파이선 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러리이다. 비록 최근에 텐서플로, 케라스 등 딥러닝 전문 라이브러리의 강세로 인해 대중적 관심이 줄어들고는 있지만 여전히 많은 데이터 분석가가 의존하는 대표적 파이썬 ML라이브러리이다.

* 파이썬 기반의 다른 머신러닝 패키지도 사이킷런 스타일의 API를 지향할 정도로 쉽고 가장 파이썬스러운 API를 제공한다.


* 머신러닝을 위한 매우 다양한 알고리즘과 개발을 위한 편리한 프레임워크와 API를 제공한다.


* 오랜 기간 실전 환경에서 검증됐으며, 매우 많은 환경에서 사용되는 성숙한 라이브러리이다. 

### conda install scikit-learn 

!pip를 이용하면 다음과 같이 설치가 가능하다. 

!pip install scikit-learn 

In [1]:
import sklearn
print(sklearn.__version__)

1.0.2


## 02 첫 번째 머신러닝 만들어 보기 ㅡ 붓꽃 품종 예측하기

사이킷런을 통해 첫 번째로 만들어볼 머신러닝 모델은 붓꽃 데이터 세트로 붓꽃의 품종을 분류(Classification)하는 것이다. 붓꽃 데이터 세트는 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 피쳐(feature)를 기반으로 꽃의 품종을 예측하기 위한 것이다.  

In [3]:
from sklearn.datasets import load_iris # data set 로딩
from sklearn.tree import DecisionTreeClassifier # 의사결정나무 분류기
from sklearn.model_selection import train_test_split # 학습데이터와 테스트데이터 분할

import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score as acc_sc # 평가지표!!!

In [15]:
iris = load_iris() # 메타데이터를 포함한 전체데이터

iris_data = iris.data # X값들... whole X_data
iris_target = iris.target # y값들 .. whole y_data

print('iris target 값:', iris_target)
print('iris target 명:', iris.target_names)

# iris_df 생성
iris_df = pd.DataFrame(iris_data,columns=iris.feature_names)
iris_df.head()
iris_df['y_label'] = iris_target
iris_df.head()

iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   y_label  
0        0  
1        0  
2        0  
3        0  
4        0

In [74]:
iris_df['sepal length (cm)'].value_counts()

5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: sepal length (cm), dtype: int64

In [61]:
# train_test_split의 용례

test_array = np.arange(1,11)
test_array2 = np.arange(101,111)
train_test_split(test_array,test_array2,test_size=0.2,random_state=156)

[array([ 9,  1,  2, 10,  4,  8,  6,  3]),
 array([7, 5]),
 array([109, 101, 102, 110, 104, 108, 106, 103]),
 array([107, 105])]

In [63]:
from sklearn.model_selection import train_test_split # 학습데이터와 테스트데이터 분할
X_train,X_test, y_train,y_test = train_test_split(iris_data,iris_target,test_size=0.2,random_state=11)

In [64]:
print(X_train.shape)
print(X_test.shape) # --> 어떠한 값을 예측함

(120, 4)
(30, 4)


In [65]:
print(y_train.shape)
print(y_test.shape)

(120,)
(30,)


In [66]:
# 의사결정나무 객체화
dt_clf = DecisionTreeClassifier(random_state=11)

In [67]:
# 학습수행
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [69]:
# 학습된 알고리즘(dt_clf)을 통해 예측을 수행
pred_dt = dt_clf.predict(X_test)

In [70]:
from sklearn.metrics import accuracy_score as acc_sc
print('예측 정확도:{0}'.format(acc_sc(y_test,pred_dt)))

예측 정확도:0.9333333333333333


## 03. train_test_split을 하지 않는다면?

In [75]:
from sklearn.datasets import load_iris # data set 로딩
from sklearn.tree import DecisionTreeClassifier # 의사결정나무 분류기
from sklearn.model_selection import train_test_split # 학습데이터와 테스트데이터 분할
from sklearn.metrics import accuracy_score as acc_sc # 평가지표!!!

import pandas as pd
import numpy as np

In [78]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
X_train = iris.data # X값 전체
y_train = iris.target # y값 전체

In [79]:
# 학습수행
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [82]:
pred_dummy_dt = dt_clf.predict(X_train)

In [83]:
y_train == pred_dummy_dt

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [84]:
acc_sc(y_train,pred_dummy_dt)

1.0

정확도가 100%이다. 뭔가 이상하다.

위의 예측 결과가 100% 정확한 이유는 이미 학습한 학습 데이터 세트를 기반으로 예측했기 때문이다. 즉, 모의고사를 이미 한 번 보고 답을 알고 있는 상태에서 모의고사 문제와 똑같은 본고사 문제가 출제됐기 때문이다. 따라서 예측을 수행하는 데이터 세트는 학습을 수행한 학습용 데이터 세트가 아닌 전용의 테스트 데이터 세트여야 한다. 사이킷런의 train_test_split()를 통해 원본 데이터 세트에서 학습 및 테스트 데이터 세트를 쉽게 분리할 수 있다. 

In [ ]:
# 그래서 결국에 train과 test를 분리하여야 한다... -> 홀드아웃(hold_out)