# Array 복습

## Array

In [249]:
import numpy as np

### 1차원 행렬 예제

In [259]:
array = np.array([1,2,3])
print(array)
print(type(array))
print(array.shape)
print(array.ndim)
print(len(array))
print(array.dtype)
array_int = array.astype('float64')
print(array_int.dtype)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
3
int32
float64


### 2차원 행렬 예제

In [261]:
array = np.array([[1,2,3]])
print(array)
print(type(array))
print(array.shape)
print(array.ndim)
print(len(array))
print(array.dtype)
array_int = array.astype('float64')
print(array_int.dtype)

[[1 2 3]]
<class 'numpy.ndarray'>
(1, 3)
2
1
int32
float64


### 3차원 행렬 예제

In [262]:
array = np.array([[[1,2,3]]])
print(array)
print(type(array))
print(array.shape)
print(array.ndim)
print(len(array))
print(array.dtype)
array_int = array.astype('float64')
print(array_int.dtype)

[[[1 2 3]]]
<class 'numpy.ndarray'>
(1, 1, 3)
3
1
int32
float64


## for문을 이용한 range 함수

In [271]:
for i in range(10):
    print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [273]:
for i in range(10,20):
    print(i, end=' ')

10 11 12 13 14 15 16 17 18 19 

### Sequence Array(Arange Array) 예제

In [285]:
sq_array = np.arange(10)
print(sq_array)
print(type(sq_array))
print(sq_array.shape)
print(sq_array.ndim)
print(len(sq_array))
print(sq_array.dtype)
sqarray_int = sq_array.astype('float64')
print(sqarray_int.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
1
10
int32
float64


### Zeros Array 예제
* 1차원은 괄호
* 2~3차원은 괄호안에 괄호

#### 1차원 Zeros Array

In [313]:
zero_array = np.zeros(5)
print(zero_array)
print(zero_array.shape)
print(zero_array.ndim)

[0. 0. 0. 0. 0.]
(5,)
1


#### 2차원 Zeros Array

In [318]:
zero_array = np.zeros((3,3))
print(zero_array)
print(zero_array.shape)
print(zero_array.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
2


#### 3차원 Zeros Array

In [325]:
zero_array = np.zeros((1,2,3))
print(zero_array)
print(zero_array.shape)
print(zero_array.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]]]
(1, 2, 3)
3


### Ones Array 예제

#### 1차원 Ones Array

In [331]:
one_array = np.ones(5)
print(one_array)
print(one_array.shape)
print(one_array.ndim)

[1. 1. 1. 1. 1.]
(5,)
1


#### 2차원 Ones Array

In [339]:
one_array = np.ones((3,3))
print(one_array)
print(one_array.shape)
print(one_array.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
2


#### 3차원 Ones Array

In [345]:
one_array = np.ones((1,2,3))
print(one_array)
print(one_array.shape)
print(one_array.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]]]
(1, 2, 3)
3


#### reshape :: 지금 갖고 있는 행렬의 모양을 바꿔준다

In [358]:
array = np.arange(10)
print(array)

print(array.reshape(2,5))
print(array.reshape(5,2))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
