In [2]:
import pandas as pd
titan_df = pd.read_csv('../train.csv')

In [3]:
titan_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
# descdribe() :: 수치형 변수들만을 기준으로 카운트, 평균, 표준편차, 최소/최대값, 4분위 수를 기준으로
#                25%, 50%, 75% 에 해당하는 값들을 테이블로 출력해준다.
titan_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
titan_df['test']='test'
titan_df.drop('test',axis=1,inplace=True)

In [18]:
pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)

print('### before axis 0 ###')
print(titan_df.head())

titan_df.drop([0,2,4], axis=0, inplace=True)

### before axis 0 ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500   NaN        S


In [19]:
print('### after axis 0 ###')
print(titan_df.head())

### after axis 0 ###
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked
1            2         1       1  Cumings, Mr...  female  38.0      1      0  PC 17599  71.2833   C85        C
3            4         1       1  Futrelle, M...  female  35.0      1      0    113803  53.1000  C123        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0    330877   8.4583   NaN        Q
6            7         0       1  McCarthy, M...    male  54.0      0      0     17463  51.8625   E46        S
7            8         0       3  Palsson, Ma...    male   2.0      3      1    349909  21.0750   NaN        S


### Axis=0 과 Axis=1 를 Numpy 를 통해 비교

In [24]:
import numpy as np
array1 = np.array([3,1,9,5])

np.sort(array1)[::-1] # 내림차순


array([9, 5, 3, 1])

In [33]:
# 어려우면
## pandas 내에서는 ...
# axis = 0 :: 행
# axis = 1 :: 열

# axis 이해하기
array2d = np.array([[8,12],
         [7,1]])

axis0_array2d = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', axis0_array2d)

axis1_array2d = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', axis1_array2d)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### DataFrame과 list, dictionary, numpy ndarray 상호변환

In [37]:
import numpy as np
import pandas as pd

In [46]:
col_name1 = ['col1']
l1 = [1,2,3]
a1 = np.array(l1)

# list를 활용하여 df생성
df_l1 = pd.DataFrame(l1,columns = col_name1)
print('1차원 리스트로 생성된 df:\n', df_l1)

# ndarray 를 통해 df 생성
df_a1 = pd.DataFrame(a1,columns = col_name1)
print('1차원 ndarray 로 생성된 df:\n', df_a1)

# dict 를 통해 df 생성
dict1 = {'col1':[1,2,3]}
df_dict1 = pd.DataFrame(dict1)
print('1차원 dictionary 로 생성된 df:\n', df_dict1)

1차원 리스트로 생성된 df:
    col1
0     1
1     2
2     3
1차원 ndarray 로 생성된 df:
    col1
0     1
1     2
2     3
1차원 dictionary 로 생성된 df:
    col1
0     1
1     2
2     3
