In [5]:
#!pip 문법 :: python 문법
!pip install sklearn

You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [ ]:
#anaconda 명령 :: <-- 얘를 통해서 설치를 권장
conda install scikit-learn

In [8]:
l1 =[1,2,3]
l2 =[4,5,6]
l1+l2

[1, 2, 3, 4, 5, 6]

# 넘파이:ML 주요 알고리즘 -선형대수와 통계에 기반

* Numpy는  Numerical Python을 의미하며 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표 패키지


* 루프를 사용치 않고 대량 데이터의 배열 연산이 가능


* C/C++과 같은 저수준 언어 기반의 호환 API제공

###  def 함수 ---> class ---> module ---> package ---> library

In [13]:
import numpy as np

In [19]:
a=[1,2,3]
array_a=np.array(a)
print(type(array_a))
print(type(a))

<class 'numpy.ndarray'>
<class 'list'>


In [24]:
print(a) # list
print(array_a) # array :: 배열/ 행렬 

[1, 2, 3]
[1 2 3]


In [44]:
array_a.shape # property 
array_a[1] # 최소첨자
print("array_a의 형태:", array_a)
print("array_a는 {0}차원입니다".format(array_a.ndim))
print("array_a의 shape:{0}".format(array_a.shape))

array_a의 형태: [1 2 3]
array_a는 1차원입니다
array_a의 shape:(3,)


In [46]:
array_a2 = np.array([[1,2,3],[11,22,33]]) # (,3) --(3,)??
                                          # (2,3)                                          
array_a2

print("array_a2의 형태:",'\n', array_a2)
print("array_a2는 {0}차원입니다".format(array_a2.ndim))
print("array_a2의 shape:{0}".format(array_a2.shape))

array_a2의 형태: 
 [[ 1  2  3]
 [11 22 33]]
array_a2는 2차원입니다
array_a2의 shape:(2, 3)


In [53]:
l1 = [[1,2],[3,4]]
l1[1]
len(l1)

2

In [50]:
#Q1.

array_a2 = np.array([[a],[b]]) #(
# array_a2.shape은 뭐가 나올까요?
print(array_a2.shape)
# array_a2의 차원은 어떻게 될까요?
print(array_a2.ndim)

(2,)
1


C:\Users\user\AppData\Local\Temp/ipykernel_6396/1766131746.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_a2 = np.array([[1,3],[11,22,33]])


In [58]:
# 3차원의 데이터 생성
l3 = [[[1,2,3]]]
array_3 =np.array(l3) 
array_3.ndim

# shape:: (1,3,1) vs shape:: 다르게 나온다???
#                      (1,1,3)
array_3.shape

(1, 1, 3)

In [ ]:
# 문제 1 (1, 1, 3) -> (2,1,3)
# 문제 2 (1,1,3) -> (1,2,3)

## summary :: 넘파이 기초 요약

In [62]:
import numpy as np # 축약어

a = [1,2,3]
array1 = np.array(a)
print('array1의 type:', type(array1))
print('array1의 shape:', array1.shape) # (3,)

array1의 type: <class 'numpy.ndarray'>
array1의 shape: (3,)


In [67]:
array2d = np.array([[1,2,3,],
                   [11,22,33]])

print('array2d의 type:', type(array2d))
print('array2d의 shape:', array2d.shape) # (2,3)

array3d = np.array([[[1,2,3]]])

print('array3d의 type:', type(array3d))
print('array3d의 shape:', array3d.shape) # (1,1,3)

# 예제풀이
문제 = np.array([[[1,2,3],[4,5,6]]])
문제.shape

array2d의 type: <class 'numpy.ndarray'>
array2d의 shape: (2, 3)
array3d의 type: <class 'numpy.ndarray'>
array3d의 shape: (1, 1, 3)


(1, 2, 3)

In [73]:
# 데이터 타입을 살펴보기
l1 = [1,2,'test']
array2 = np.array(l1)
print(array2, array2.dtype)

l2 = [1,2,3.5]
array3 = np.array(l2)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1.  2.  3.5] float64


In [83]:
# 데이터 타입을 살펴보기
array_int = np.array([1,2,3])
array_float = array_int.astype('float64') 
print(array_float,array_float.dtype) # int32 -> float64

array_int1 = array_float.astype('int32')
print(array_int1,array_int1.dtype) # float64 -> int32 

array_float1 = np.array([1.1,2.2,3.3])
print(array_float1.astype('int32'))

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3]


## ndarray에도 편리하게 생성하는 - arange, zeros, ones

In [87]:
# 파이썬 for문을 공부할 때 
# 우리는 range라는 코드를 살펴봄
for i in range(3,10):
    print(i, end=' ')

3 4 5 6 7 8 9 

In [94]:
# 시퀀스 array 
sq_array = np.arange(10)
print(sq_array.dtype, sq_array.shape)

int32 (10,)


In [101]:
# zeros 활용
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape,'\n')

# ones 활용
one_array = np.ones((3,2),dtype='int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


In [110]:
#reshape :: 지금 여러분이 갖고 있는 행렬의 모양을 바꿔줍니다.

array1 = np.arange(10)
print(array1) # 몇 차원????

#reshape :: 지금 행렬의 모양을 바꿔줌
print(array1.reshape(-1,5))
print(array1.reshape(-1,2))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [133]:
array_3 = np.arange(4)
array_3.shape
array_3.reshape(-1,2) # -1을 쓰는 이유는 시인성 및 가독성이 떨어지기 때문...

array([[0, 1],
       [2, 3]])